// Semantic, per-UI-area color tokens built from a brand's raw colors.json
// scale (brands/<brand>/theme/colors.json - primary/secondary/featured,
// text, background). This is the ONLY place that decides "which shade of
// the brand's palette does the QuickReply chip use" - components never
// read colors.json/raw hex directly, they read
// theme.componentPalette.<area>.<token> instead (see defaultTheme.js for
// the brand-agnostic fallback shape this replaces once a brand resolves).
//
// `colors` here is brandInfo.config.colors, generated by
// scripts/prepare-brand.js's getBrandColorPalette() - it always has
// primary500/primary800 populated (with prepare-brand.js's own fallback
// chain baked in), plus the full colors.json scale when a brand has set
// one up.
function buildComponentPalette(colors = {}) {
  const primary = colors.primary || {};
  const featured = colors.featured || {};

  const primary500 = colors.primary500 || primary['500'] || '#3F5773';
  const primary800 = colors.primary800 || primary['800'] || primary500;

  return {
    launcher: {
      color: primary500,
      hoverColor: primary800,
      text: {
        color: '#ffffff',
      },
    },
    header: {
      backgroundColor: primary500,
      textColor: '#ffffff',
    },
    button: {
      primary: {
        backgroundColor: primary500,
        hoverBackgroundColor: primary800,
      },
    },
    // Chip (QuickReply options): per the Figma "Chips" spec, background/
    // border/text colors are neutral and stay fixed across every brand -
    // unlike the rest of this palette, these are literal, not derived from
    // colors.primary/featured. Only the font-family (theme.typography.label,
    // which doesn't set one) follows the brand's typeface.
    quickReply: {
      backgroundColor: '#FFFFFF',
      borderColor: '#1A1A1A',
      textColor: '#1A1A1A',
      hoverBackgroundColor: '#F2F2F2',
      hoverBorderColor: '#1A1A1A',
      activeBackgroundColor: '#D9D9D9',
      activeBorderColor: '#D9D9D9',
      focusBorderColor: '#6D9CCF',
      disabledBackgroundColor: '#FBFBFB',
      disabledBorderColor: '#DDDDDD',
      disabledTextColor: '#BFBFBF',
    },
    timePicker: {
      confirmBackgroundColor: primary500,
      confirmTextColor: '#ffffff',
    },
    carousel: {
      arrowBackgroundColor: '#ffffff',
    },
    // Recording/privacy disclaimer above the composer: neutral by default
    // (see defaultTheme.js palette.whisper), but its background is meant to
    // pick up the brand's light "featured" tint while the consumer is
    // actively engaging with the input field (Figma: "neutral at default
    // but becomes brand-specific with interaction"). featured-200/100 is a
    // light tint (not primary500, which is near-black for most brands and
    // would fail text contrast as a background fill).
    disclaimer: {
      activeBackgroundColor: featured['200'] || featured['100'] || primary500,
    },
  };
}

// Mirrors scripts/prepare-brand.js's getBubbleColors() so the direct-embed
// path (theme.chatTranscriptor, read by ChatMessage.js/ChatComposer.js/
// InteractiveMessage.js) and the hosted-widget iframe path (the
// --ac-widget-transcript-*-bubble-color CSS vars written into
// brand-theme.css) resolve bubble colors from the same colors.json
// `bubbles.customer` / `bubbles.agent` keys instead of drifting apart.
// Brands without a `bubbles` key keep the original hardcoded look.
function buildChatTranscriptorPalette(colors = {}) {
  const bubbles = colors.bubbles || {};
  const customer = bubbles.customer || {};
  const agent = bubbles.agent || {};
  const featured = colors.featured || {};

  const primary500 =
    colors.primary500 ||
    (colors.primary && colors.primary["500"]) ||
    "#3F5773";

  const customerBg =
    customer.background ||
    featured["300"] ||
    primary500;

  const customerText = customer.text || "#FFFFFF";
  const agentBg = agent.background || "#F5F5F5";
  const agentText = agent.text || "#333333";

  // Send button's active fill follows the brand's featured-400 swatch,
  // one step darker than the bubble's featured-300 - keeps it visually
  // related to the bubble color without being identical to it.
  const sendButtonActiveBg = featured["400"] || primary500;

  return {
    outgoingMsgBg: customerBg,
    incomingMsgBg: agentBg,
    sendButtonActiveBg,
    outgoingMsg: `
      color: ${customerText};
      background: ${customerBg};
    `,
    incomingMsg: `
      color: ${agentText};
      background: ${agentBg};
    `,
  };
}

export default buildComponentPalette;
export {buildChatTranscriptorPalette};
