// Semantic, per-UI-area color tokens built from a brand's raw colors.json
// scale (brands/<brand>/theme/colors.json - primary/secondary/featured,
// text, background). This is the ONLY place that decides "which shade of
// the brand's palette does the QuickReply chip use" - components never
// read colors.json/raw hex directly, they read
// theme.componentPalette.<area>.<token> instead (see defaultTheme.js for
// the brand-agnostic fallback shape this replaces once a brand resolves).
//
// `colors` here is brandInfo.config.colors, generated by
// scripts/prepare-brand.js's getBrandColorPalette() - it always has
// primary500/primary800 populated (with prepare-brand.js's own fallback
// chain baked in), plus the full colors.json scale when a brand has set
// one up.
function buildComponentPalette(colors = {}) {
  const primary = colors.primary || {};
  const text = colors.text || {};

  const primary500 = colors.primary500 || primary['500'] || '#3F5773';
  const primary800 = colors.primary800 || primary['800'] || primary500;
  const textDefault = text.default || '#1A1A1A';

  return {
    launcher: {
      color: primary500,
      hoverColor: primary800,
      text: {
        color: '#ffffff',
      },
    },
    header: {
      backgroundColor: primary500,
      textColor: '#ffffff',
    },
    button: {
      primary: {
        backgroundColor: primary500,
        hoverBackgroundColor: primary800,
      },
    },
    quickReply: {
      // A light tint of the brand color (not solid primary500) to keep the
      // original "pastel chip" look - only the hue now follows the brand
      // instead of a fixed, brand-unrelated lavender.
      backgroundColor: primary['100'] || primary500,
      hoverBackgroundColor: primary['200'] || primary800,
      textColor: textDefault,
    },
    timePicker: {
      confirmBackgroundColor: primary500,
      confirmTextColor: '#ffffff',
    },
    carousel: {
      // Kept neutral white (not brand-colored) to preserve the existing
      // look of the round scroll-arrow control - named here so it can
      // become brand-driven later with a one-line change if ever wanted.
      arrowBackgroundColor: '#ffffff',
    },
  };
}

// Mirrors scripts/prepare-brand.js's getBubbleColors() so the direct-embed
// path (theme.chatTranscriptor, read by ChatMessage.js/ChatComposer.js/
// InteractiveMessage.js) and the hosted-widget iframe path (the
// --ac-widget-transcript-*-bubble-color CSS vars written into
// brand-theme.css) resolve bubble colors from the same colors.json
// `bubbles.customer` / `bubbles.agent` keys instead of drifting apart.
// Brands without a `bubbles` key keep the original hardcoded look.
function buildChatTranscriptorPalette(colors = {}) {
  const bubbles = colors.bubbles || {};
  const customer = bubbles.customer || {};
  const agent = bubbles.agent || {};

  const primary500 = colors.primary500 || (colors.primary && colors.primary['500']) || '#3F5773';
  const customerBg = customer.background || primary500;
  const customerText = customer.text || '#FFFFFF';
  const agentBg = agent.background || '#F5F5F5';
  const agentText = agent.text || '#333333';

  return {
    outgoingMsgBg: customerBg,
    incomingMsgBg: agentBg,
    outgoingMsg: `
      color: ${customerText};
      background: ${customerBg};
      `,
    incomingMsg: `
      color: ${agentText};
      background: ${agentBg};
      `,
  };
}

export default buildComponentPalette;
export {buildChatTranscriptorPalette};
