#!/usr/bin/env node

/**
 * Client Environment Preparation Script
 * 
 * This script prepares the local-testing environment for a specific client and environment.
 * It copies client-specific assets, themes, and configurations to the runtime folder.
 * 
 * Usage: node scripts/prepare-client.js --client=abc-corp --env=dev
 */

const fs = require('fs');
const path = require('path');

// Parse command line arguments
function parseArgs() {
  const args = {};
  process.argv.slice(2).forEach(arg => {
    if (arg.startsWith('--')) {
      const [key, value] = arg.slice(2).split('=');
      args[key] = value;
    }
  });
  return args;
}

// Validate client and environment exist
function validateClientEnv(clientName, envName) {
  const clientPath = path.join(__dirname, '..', 'clients', clientName);
  const envFile = path.join(clientPath, 'config', `env.${envName}.json`);
  
  if (!fs.existsSync(clientPath)) {
    console.error(`❌ Client "${clientName}" not found in clients/ folder`);
    console.log('\nAvailable clients:');
    listClients();
    process.exit(1);
  }
  
  if (!fs.existsSync(envFile)) {
    console.error(`❌ Environment "${envName}" not found for client "${clientName}"`);
    console.log('\nAvailable environments:');
    listEnvironments(clientName);
    process.exit(1);
  }
  
  return {clientPath, envFile};
}

// List available clients
function listClients() {
  const clientsDir = path.join(__dirname, '..', 'clients');
  const clients = fs.readdirSync(clientsDir)
    .filter(name => {
      const fullPath = path.join(clientsDir, name);
      return fs.statSync(fullPath).isDirectory() && !name.startsWith('_');
    });
  
  if (clients.length === 0) {
    console.log('  No clients configured yet. Use "npm run create-client" to create one.');
  } else {
    clients.forEach(client => console.log(`  - ${client}`));
  }
}

// List available environments for a client
function listEnvironments(clientName) {
  const configDir = path.join(__dirname, '..', 'clients', clientName, 'config');
  if (!fs.existsSync(configDir)) {
    console.log('  No configurations found');
    return;
  }
  
  const envFiles = fs.readdirSync(configDir)
    .filter(name => name.startsWith('env.') && name.endsWith('.json'))
    .map(name => name.replace('env.', '').replace('.json', ''));
  
  envFiles.forEach(env => console.log(`  - ${env}`));
}

// Copy directory recursively
function copyDirSync(src, dest) {
  if (!fs.existsSync(src)) return;
  
  fs.mkdirSync(dest, {recursive: true});
  
  const entries = fs.readdirSync(src, {withFileTypes: true});
  
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    
    if (entry.isDirectory()) {
      copyDirSync(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

// Generate backendEndpoint.js from config
// Generate backendEndpoint.js from config
function generateBackendEndpoint(config, outputPath) {
  const content = `/**
  * Backend Endpoint Configuration
  * Auto-generated by prepare-client.js
  * 
  * Client: ${config._meta.client}
  * Environment: ${config.environment}
  * Generated: ${new Date().toISOString()}
  * 
  * DO NOT EDIT MANUALLY - Changes will be overwritten
  * Edit the source config at: clients/${config._meta.client}/config/env.${config.environment}.json
  */

  var contactFlowId = "${config.aws.contactFlowId}";
  var instanceId = "${config.aws.instanceId}";
  var apiGatewayEndpoint = "${config.aws.apiGatewayEndpoint}";
  var snippetId = "${config.aws.snippetId}";
  var region = "${config.aws.region}";

  // Additional config (optional - for enhanced widget features)
  var widgetConfig = {
    title: "${config.widget.title}",
    subtitle: "${config.widget.subtitle}",
    primaryColor: "${config.widget.primaryColor}",
    secondaryColor: "${config.widget.secondaryColor}",
    headerTextColor: "${config.widget.headerTextColor}",
    fontFamily: "${config.widget.fontFamily}"
  };

  var featureFlags = {
    enableAttachments: ${config.features.enableAttachments},
    enableTypingIndicator: ${config.features.enableTypingIndicator},
    enableReadReceipts: ${config.features.enableReadReceipts},
    enableSounds: ${config.features.enableSounds}
  };
  `;

  fs.writeFileSync(outputPath, content);
  console.log(`  ✅ Generated backendEndpoint.js`);
}

function getFontFamilyName(fontFamilyString) {
  if (!fontFamilyString) return 'CustomFont';
  const family = fontFamilyString.split(',')[0].trim();
  return family.replace(/^['"]|['"]$/g, '') || 'CustomFont';
}

function generateFontFaceCss(fontFamilyString, fontFiles) {
  if (!fontFiles || fontFiles.length === 0) {
    return '';
  }

  const fontFamily = getFontFamilyName(fontFamilyString);
  const sortedFiles = fontFiles.slice().sort((a, b) => a.ext.localeCompare(b.ext));
  const srcLines = sortedFiles.map(font => {
    const formatMap = {
      woff2: 'woff2',
      woff: 'woff',
      ttf: 'truetype',
      otf: 'opentype'
    };
    return `url('./client-assets/${font.relativePath}') format('${formatMap[font.ext] || 'truetype'}')`;
  });

  return `@font-face {
  font-family: '${fontFamily}';
  src: ${srcLines.join(',\n       ')};
  font-weight: normal;
  font-style: normal;
}

`;
}

function getClientFontFiles(fontsDir) {
  if (!fs.existsSync(fontsDir)) {
    return [];
  }

  const supported = ['.ttf', '.woff', '.woff2', '.otf'];

  function scanDir(directory, parentRelative = '') {
    const files = [];
    const entries = fs.readdirSync(directory, {withFileTypes: true});
    for (const entry of entries) {
      const entryPath = path.join(directory, entry.name);
      const relativePath = path.join(parentRelative, entry.name).replace(/\\/g, '/');
      if (entry.isDirectory()) {
        files.push(...scanDir(entryPath, relativePath));
      } else if (supported.includes(path.extname(entry.name).toLowerCase())) {
        files.push({
          name: entry.name,
          relativePath,
          ext: path.extname(entry.name).slice(1).toLowerCase()
        });
      }
    }
    return files;
  }

  return scanDir(fontsDir, 'Fonts');
}

function generateClientThemeCss(widgetConfig, headerConfig, outputPath, fontFiles = []) {
  const primaryColor = widgetConfig.primaryColor || '#3F51B5';
  const secondaryColor = widgetConfig.secondaryColor || '#FF4081';
  const headerTextColor = widgetConfig.headerTextColor || '#FFFFFF';
  const fontFamily = widgetConfig.fontFamily || 'Arial, sans-serif';

  const headerBg            = (headerConfig && headerConfig.backgroundColor) || '#1a2340';
  const headerTitleColor    = (headerConfig && headerConfig.textColor)        || headerTextColor;
  const headerSubtitleColor = (headerConfig && headerConfig.subtitleColor)    || 'rgba(255,255,255,0.70)';

  const fontFaceCss = generateFontFaceCss(fontFamily, fontFiles);

  const content = `${fontFaceCss}:root {
  --ac-widget-header-backgroundcolor: ${primaryColor};
  --ac-widget-header-textcolor: ${headerTextColor};
  --ac-widget-footer-backgroundcolor: ${secondaryColor};
  --ac-widget-footer-button-backgroundcolor: ${secondaryColor};
  --ac-widget-footer-button-textcolor: ${headerTextColor};
  --ac-widget-global-typeface: ${fontFamily};
  --ac-widget-transcript-customer-bubble-color: ${primaryColor};
  --ac-widget-transcript-customer-textcolor: ${headerTextColor};
  --ac-widget-transcript-agent-bubble-color: #F5F5F5;
  --ac-widget-transcript-agent-textcolor: #333333;

  /* ── Chat Header ── */
  --header-bg:             ${headerBg};
  --header-text-color:     ${headerTitleColor};
  --header-subtitle-color: ${headerSubtitleColor};
  --header-padding:        14px 16px;
  --header-logo-size:      40px;
  --header-title-size:     13px;
  --header-title-weight:   600;
  --header-title-spacing:  0.08em;
  --header-subtitle-size:  11px;
  --header-subtitle-maxw:  260px;
  --header-close-size:     22px;
}
`;

  fs.writeFileSync(outputPath, content);
  console.log(`  ✅ Generated client-theme.css`);
}

function getClientLogoUrl(clientPath) {
  const logos = ['logo.png', 'logo.svg', 'assets/logo.png', 'assets/images/logo.png'];
  for (const fileName of logos) {
    const logoPath = path.join(clientPath, fileName);
    if (fs.existsSync(logoPath)) {
      const relativePath = path.relative(clientPath, logoPath).replace(/\\/g, '/');
      return `./client-assets/${relativePath}`;
    }
  }
  return null;
}

// Generate client info file for runtime reference
function generateClientInfo(clientName, envName, config, outputPath, logoUrl) {
  const info = {
    client: clientName,
    environment: envName,
    generatedAt: new Date().toISOString(),
    config: {
      ...config.widget,
      header:              config.header || {},
      apiGatewayEndpoint:  config.aws?.apiGatewayEndpoint || '',
      instanceId:          config.aws?.instanceId || '',
      contactFlowId:       config.aws?.contactFlowId || '',
      header: config.header || {},
    },
  };

  if (logoUrl) {
    info.assets = {logo: logoUrl};
  }

  const content = `/**
 * Current Client Configuration
 * Auto-generated - Do not edit manually
 */
window.__CHAT_CLIENT_INFO__ = ${JSON.stringify(info, null, 2)};
`;

  fs.writeFileSync(outputPath, content);
  console.log(`  ✅ Generated clientInfo.js`);
}

// Main execution
function main() {
  const args = parseArgs();
  
  // Check for help flag
  if (args.help || args.h) {
    console.log(`
Client Environment Preparation Script

Usage:
  npm run prepare -- --client=<client-name> --env=<environment>
  node scripts/prepare-client.js --client=<client-name> --env=<environment>

Options:
  --client    Client folder name (required)
  --env       Environment name: dev, qa, prod, etc. (required)
  --list      List all available clients
  --help, -h  Show this help message

Examples:
  npm run prepare -- --client=abc-corp --env=dev
  npm run prepare -- --client=xyz-bank --env=prod
  npm run prepare -- --list
`);
    process.exit(0);
  }
  
  // List clients if requested
  if (args.list) {
    console.log('\n📁 Available Clients:\n');
    listClients();
    console.log('');
    process.exit(0);
  }
  
  // Validate required arguments
  if (!args.client || !args.env) {
    console.error('❌ Missing required arguments: --client and --env\n');
    console.log('Usage: npm run prepare -- --client=<client-name> --env=<environment>');
    console.log('Example: npm run prepare -- --client=abc-corp --env=dev');
    console.log('\nRun with --help for more options');
    process.exit(1);
  }
  
  const clientName = args.client;
  const envName = args.env;
  
  console.log(`\n🚀 Preparing environment for client: ${clientName} (${envName})\n`);
  
  // Validate client and environment
  const {clientPath, envFile} = validateClientEnv(clientName, envName);
  
  // Read environment configuration
  const config = JSON.parse(fs.readFileSync(envFile, 'utf8'));
  config._meta = {client: clientName};
  
  // Define paths
  const localTestingDir = path.join(__dirname, '..', 'local-testing');
  const clientAssetsDir = path.join(clientPath, 'assets');
  const clientThemeDir = path.join(clientPath, 'theme');
  const clientFontsDir = path.join(clientPath, 'Fonts');
  const outputAssetsDir = path.join(localTestingDir, 'client-assets');

  // Clean previous client assets
  if (fs.existsSync(outputAssetsDir)) {
    fs.rmSync(outputAssetsDir, {recursive: true});
    console.log('  🧹 Cleaned previous client assets');
  }

  // Copy client assets
  if (fs.existsSync(clientAssetsDir)) {
    copyDirSync(clientAssetsDir, outputAssetsDir);
    console.log('  ✅ Copied client assets');
  }

  // Copy theme files
  if (fs.existsSync(clientThemeDir)) {
    copyDirSync(clientThemeDir, path.join(outputAssetsDir, 'theme'));
    console.log('  ✅ Copied theme files');
  }

  // Copy font files for client-specific font families
  if (fs.existsSync(clientFontsDir)) {
    copyDirSync(clientFontsDir, path.join(outputAssetsDir, 'Fonts'));
    console.log('  ✅ Copied font assets');
  }

  const fontFiles = getClientFontFiles(clientFontsDir);

  // Generate configuration files
  generateBackendEndpoint(config, path.join(localTestingDir, 'backendEndpoint.js'));

  const logoUrl = getClientLogoUrl(clientPath);
  generateClientInfo(clientName, envName, config, path.join(localTestingDir, 'clientInfo.js'), logoUrl);
  generateClientThemeCss(config.widget, config.header || {}, path.join(localTestingDir, 'client-theme.css'), fontFiles);
  const envStateFile = path.join(__dirname, '..', '.client-env');
  fs.writeFileSync(envStateFile, JSON.stringify({client: clientName, env: envName}, null, 2));
  console.log('  ✅ Saved current client/env state');
  
  console.log(`\n✨ Environment ready! Client: ${clientName}, Env: ${envName}`);
  console.log(`   Run "npm run dev" to start the development server\n`);
}

// Run
main();
