#!/usr/bin/env node

/**
 * Client Environment Preparation Script
 * 
 * This script prepares the local-testing environment for a specific client and environment.
 * It copies client-specific assets, themes, and configurations to the runtime folder.
 * 
 * Usage: node scripts/prepare-client.js --client=abc-corp --env=dev
 */

const fs = require('fs');
const path = require('path');

// Parse command line arguments
function parseArgs() {
  const args = {};
  process.argv.slice(2).forEach(arg => {
    if (arg.startsWith('--')) {
      const [key, value] = arg.slice(2).split('=');
      args[key] = value;
    }
  });
  return args;
}

// Validate client and environment exist
function validateClientEnv(clientName, envName) {
  const clientPath = path.join(__dirname, '..', 'clients', clientName);
  const envFile = path.join(clientPath, 'config', `env.${envName}.json`);
  
  if (!fs.existsSync(clientPath)) {
    console.error(`❌ Client "${clientName}" not found in clients/ folder`);
    console.log('\nAvailable clients:');
    listClients();
    process.exit(1);
  }
  
  if (!fs.existsSync(envFile)) {
    console.error(`❌ Environment "${envName}" not found for client "${clientName}"`);
    console.log('\nAvailable environments:');
    listEnvironments(clientName);
    process.exit(1);
  }
  
  return {clientPath, envFile};
}

// List available clients
function listClients() {
  const clientsDir = path.join(__dirname, '..', 'clients');
  const clients = fs.readdirSync(clientsDir)
    .filter(name => {
      const fullPath = path.join(clientsDir, name);
      return fs.statSync(fullPath).isDirectory() && !name.startsWith('_');
    });
  
  if (clients.length === 0) {
    console.log('  No clients configured yet. Use "npm run create-client" to create one.');
  } else {
    clients.forEach(client => console.log(`  - ${client}`));
  }
}

// List available environments for a client
function listEnvironments(clientName) {
  const configDir = path.join(__dirname, '..', 'clients', clientName, 'config');
  if (!fs.existsSync(configDir)) {
    console.log('  No configurations found');
    return;
  }
  
  const envFiles = fs.readdirSync(configDir)
    .filter(name => name.startsWith('env.') && name.endsWith('.json'))
    .map(name => name.replace('env.', '').replace('.json', ''));
  
  envFiles.forEach(env => console.log(`  - ${env}`));
}

// Copy directory recursively
function copyDirSync(src, dest) {
  if (!fs.existsSync(src)) return;
  
  fs.mkdirSync(dest, {recursive: true});
  
  const entries = fs.readdirSync(src, {withFileTypes: true});
  
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    
    if (entry.isDirectory()) {
      copyDirSync(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

// Generate backendEndpoint.js from config
// Generate backendEndpoint.js from config
function generateBackendEndpoint(config, outputPath) {
  const content = `/**
  * Backend Endpoint Configuration
  * Auto-generated by prepare-client.js
  * 
  * Client: ${config._meta.client}
  * Environment: ${config.environment}
  * Generated: ${new Date().toISOString()}
  * 
  * DO NOT EDIT MANUALLY - Changes will be overwritten
  * Edit the source config at: clients/${config._meta.client}/config/env.${config.environment}.json
  */

  var contactFlowId = "${config.aws.contactFlowId}";
  var instanceId = "${config.aws.instanceId}";
  var apiGatewayEndpoint = "${config.aws.apiGatewayEndpoint}";
  var snippetId = "${config.aws.snippetId}";
  var region = "${config.aws.region}";

  // Additional config (optional - for enhanced widget features)
  var widgetConfig = {
    title: "${config.widget.title}",
    subtitle: "${config.widget.subtitle}",
    primaryColor: "${config.widget.primaryColor}",
    secondaryColor: "${config.widget.secondaryColor}",
    headerTextColor: "${config.widget.headerTextColor}",
    fontFamily: "${config.widget.fontFamily}"
  };

  var featureFlags = {
    enableAttachments: ${config.features.enableAttachments},
    enableTypingIndicator: ${config.features.enableTypingIndicator},
    enableReadReceipts: ${config.features.enableReadReceipts},
    enableSounds: ${config.features.enableSounds}
  };
  `;

  fs.writeFileSync(outputPath, content);
  console.log(`  ✅ Generated backendEndpoint.js`);
}

function getFontFamilyName(fontFamilyString) {
  if (!fontFamilyString) return 'CustomFont';
  const family = fontFamilyString.split(',')[0].trim();
  return family.replace(/^['"]|['"]$/g, '') || 'CustomFont';
}

function getFontFamilyFromPath(relativePath) {
  const formatDirs = ['ttf', 'otf', 'woff', 'woff2'];
  const ignoredDirs = ['assets', 'fonts'];
  const parts = relativePath.split('/').filter(Boolean);

  for (let index = parts.length - 1; index >= 0; index -= 1) {
    const part = parts[index];
    const lowerPart = part.toLowerCase();

    if (!part || part.includes('.')) {
      continue;
    }

    if (formatDirs.includes(lowerPart) || ignoredDirs.includes(lowerPart)) {
      continue;
    }

    return part.replace(/_/g, ' ').trim() || 'CustomFont';
  }

  return 'CustomFont';
}

function inferFontFamilyFromClientPath(clientPath, fallback = 'CustomFont') {
  const candidateDirs = [
    path.join(clientPath, 'assets', 'fonts'),
    path.join(clientPath, 'Fonts')
  ];

  for (const fontDir of candidateDirs) {
    if (!fs.existsSync(fontDir)) {
      continue;
    }

    const childNames = fs.readdirSync(fontDir).filter(name => {
      const childPath = path.join(fontDir, name);
      return fs.existsSync(childPath) && fs.statSync(childPath).isDirectory() && !['TTF', 'OTF', 'WOFF', 'WOFF2', 'ttf', 'otf', 'woff', 'woff2'].includes(name);
    });

    if (childNames.length > 0) {
      return childNames[0].replace(/_/g, ' ').trim();
    }
  }

  return fallback;
}

function getResolvedFontFamily(fontFamilyString, fontFiles, clientPath = null) {
  const detectedFamily = Array.isArray(fontFiles)
    ? fontFiles.find(file => file.familyName && file.familyName !== 'CustomFont')?.familyName
    : null;

  if (detectedFamily) {
    return detectedFamily;
  }

  if (clientPath) {
    const inferredFamily = inferFontFamilyFromClientPath(clientPath);
    if (inferredFamily && inferredFamily !== 'CustomFont') {
      return inferredFamily;
    }
  }

  if (fontFamilyString && fontFamilyString !== 'TTF' && fontFamilyString !== 'OTF' && fontFamilyString !== 'WOFF' && fontFamilyString !== 'WOFF2') {
    return getFontFamilyName(fontFamilyString);
  }

  return 'CustomFont';
}

const FONT_FORMAT_MAP = {
  woff2: 'woff2',
  woff: 'woff',
  ttf: 'truetype',
  otf: 'opentype'
};

// Preferred src ordering within a single @font-face block (browsers use the
// first source they can load, so list the most efficient formats first).
const FONT_FORMAT_PRIORITY = ['woff2', 'woff', 'otf', 'ttf'];

const FONT_WEIGHT_MAP = {
  thin: 100, th: 100, hairline: 100,
  extralight: 200, ultralight: 200,
  light: 300, lt: 300,
  regular: 400, roman: 400, rg: 400, book: 400, normal: 400,
  medium: 500, md: 500,
  semibold: 600, demibold: 600, sb: 600,
  bold: 700, bd: 700,
  extrabold: 800, ultrabold: 800,
  black: 900, blk: 900, heavy: 900
};

// Derives font-weight/font-style from a filename's trailing token, e.g.
// "HelveticaNeueLTPro-BdIt.ttf" -> {weight: 700, style: 'italic'},
// "HelveticaNeueLTPro-Roman.ttf" -> {weight: 400, style: 'normal'}.
// Font files that don't distinguish weight in the filename all resolve to
// the same {400, normal}, which is intentional since we can't tell them apart.
function parseFontWeightStyle(fileName) {
  const base = fileName.replace(/\.[^.]+$/, '');
  const parts = base.split(/[-_\s]+/).filter(Boolean);
  const last = (parts[parts.length - 1] || '').toLowerCase();

  let style = 'normal';
  let weightToken = last;
  const italicMatch = last.match(/(italic|oblique|it)$/);
  if (italicMatch) {
    style = italicMatch[1] === 'oblique' ? 'oblique' : 'italic';
    weightToken = last.slice(0, -italicMatch[1].length);
  }

  const weight = FONT_WEIGHT_MAP[weightToken] || 400;
  return {weight, style};
}

// Descriptors describing where each client font file lives, used both to
// emit the @font-face CSS block and to hand the same data to the runtime
// (via clientInfo.js) so the widget can inject its own @font-face rules
// when it's rendered inside a cross-document iframe that never loads
// client-theme.css.
// Font files are scanned from either clients/<brand>/Fonts or
// clients/<brand>/assets/fonts, but prepare-client.js copies both of those
// source folders' *contents* into local-testing/client-assets/Fonts. Strip
// the source-root prefix so served URLs match where files actually land.
function stripFontsSourcePrefix(relativePath) {
  const parts = relativePath.split('/').filter(Boolean);
  while (parts.length && ['fonts', 'assets'].includes(parts[0].toLowerCase())) {
    parts.shift();
  }
  return parts.join('/');
}

function getFontFaceDescriptors(fontFiles, resolvedFontFamily) {
  if (!fontFiles || fontFiles.length === 0) {
    return [];
  }

  return [].concat(fontFiles)
    .sort((a, b) => a.ext.localeCompare(b.ext))
    .map(font => {
      const {weight, style} = parseFontWeightStyle(font.name);
      return {
        family: resolvedFontFamily,
        format: FONT_FORMAT_MAP[font.ext] || 'truetype',
        ext: font.ext,
        url: './client-assets/Fonts/' + stripFontsSourcePrefix(font.relativePath),
        weight,
        style
      };
    });
}

function generateFontFaceCss(fontFamilyString, fontFiles, resolvedFontFamily = null) {
  const fontFamily = resolvedFontFamily || getResolvedFontFamily(fontFamilyString, fontFiles);
  const descriptors = getFontFaceDescriptors(fontFiles, fontFamily);
  if (!descriptors.length) {
    return '';
  }

  // Group by weight/style so each distinct font file (Bold, Light, Medium, ...)
  // gets its own @font-face rule instead of being squashed into a single
  // normal-weight rule where the browser silently picks just one file.
  const byWeightStyle = descriptors.reduce((acc, font) => {
    const key = font.weight + '|' + font.style;
    acc[key] = acc[key] || [];
    acc[key].push(font);
    return acc;
  }, {});

  return Object.keys(byWeightStyle).map(key => {
    const group = byWeightStyle[key];
    const {weight, style} = group[0];
    const sources = [].concat(group)
      .sort((a, b) => FONT_FORMAT_PRIORITY.indexOf(a.ext) - FONT_FORMAT_PRIORITY.indexOf(b.ext))
      .map(font => "url('" + font.url + "') format('" + font.format + "')")
      .join(',\n       ');
    return "@font-face {\n  font-family: '" + fontFamily + "';\n  src: " + sources + ";\n  font-weight: " + weight + ";\n  font-style: " + style + ";\n}\n";
  }).join('\n') + '\n';
}

function getClientFontFiles(clientPath) {
  const supported = ['.ttf', '.woff', '.woff2', '.otf'];
  const candidateDirs = [
    path.join(clientPath, 'Fonts'),
    path.join(clientPath, 'assets', 'fonts')
  ];

  const files = [];
  const seen = new Set();

  function scanDir(directory, parentRelative = '') {
    if (!fs.existsSync(directory)) {
      return [];
    }

    const entries = fs.readdirSync(directory, {withFileTypes: true});
    const scannedFiles = [];
    for (const entry of entries) {
      const entryPath = path.join(directory, entry.name);
      const relativePath = path.join(parentRelative, entry.name).replace(/\\/g, '/');
      if (entry.isDirectory()) {
        scannedFiles.push(...scanDir(entryPath, relativePath));
      } else if (supported.includes(path.extname(entry.name).toLowerCase())) {
        const ext = path.extname(entry.name).slice(1).toLowerCase();
        const familyName = getFontFamilyFromPath(relativePath);
        scannedFiles.push({
          name: entry.name,
          relativePath,
          ext,
          familyName
        });
      }
    }
    return scannedFiles;
  }

  candidateDirs.forEach(fontsDir => {
    const scanned = scanDir(fontsDir, path.relative(clientPath, fontsDir).replace(/\\/g, '/'));
    scanned.forEach(file => {
      const key = `${file.relativePath}:${file.ext}`;
      if (!seen.has(key)) {
        seen.add(key);
        files.push(file);
      }
    });
  });

  return files;
}

function generateClientThemeCss(widgetConfig, headerConfig, outputPath, fontFiles = [], resolvedFontFamily = null) {
  const primaryColor = widgetConfig.primaryColor || '#3F51B5';
  const secondaryColor = widgetConfig.secondaryColor || '#FF4081';
  const headerTextColor = widgetConfig.headerTextColor || '#FFFFFF';
  const fontFamily = resolvedFontFamily || getResolvedFontFamily(widgetConfig.fontFamily, fontFiles);

  const headerBg = (headerConfig && headerConfig.backgroundColor) || '#1a2340';
  const headerTitleColor = (headerConfig && headerConfig.textColor) || headerTextColor;
  const headerSubtitleColor = (headerConfig && headerConfig.subtitleColor) || 'rgba(255,255,255,0.70)';

  const fontFaceCss = generateFontFaceCss(fontFamily, fontFiles, fontFamily);
  const content = fontFaceCss + ':root {\n' +
    '  --ac-widget-header-backgroundcolor: ' + primaryColor + ';\n' +
    '  --ac-widget-header-textcolor: ' + headerTextColor + ';\n' +
    '  --ac-widget-footer-backgroundcolor: ' + secondaryColor + ';\n' +
    '  --ac-widget-footer-button-backgroundcolor: ' + secondaryColor + ';\n' +
    '  --ac-widget-footer-button-textcolor: ' + headerTextColor + ';\n' +
    '  --ac-widget-global-typeface: ' + fontFamily + ';\n' +
    '  --ac-widget-transcript-customer-bubble-color: ' + primaryColor + ';\n' +
    '  --ac-widget-transcript-customer-textcolor: ' + headerTextColor + ';\n' +
    '  --ac-widget-transcript-agent-bubble-color: #F5F5F5;\n' +
    '  --ac-widget-transcript-agent-textcolor: #333333;\n\n' +
    '  /* ── Chat Header ── */\n' +
    '  --header-bg:             ' + headerBg + ';\n' +
    '  --header-text-color:     ' + headerTitleColor + ';\n' +
    '  --header-subtitle-color: ' + headerSubtitleColor + ';\n' +
    '  --header-padding:        14px 16px;\n' +
    '  --header-logo-size:      40px;\n' +
    '  --header-title-size:     13px;\n' +
    '  --header-title-weight:   600;\n' +
    '  --header-title-spacing:  0.08em;\n' +
    '  --header-subtitle-size:  11px;\n' +
    '  --header-subtitle-maxw:  260px;\n' +
    '  --header-close-size:     22px;\n' +
    '}\n';

  fs.writeFileSync(outputPath, content);
  console.log('  ✅ Generated client-theme.css');
}

function getClientLogoUrl(clientPath) {
  const logos = ['logo.png', 'logo.svg', 'assets/logo.png', 'assets/images/logo.png'];
  for (const fileName of logos) {
    const logoPath = path.join(clientPath, fileName);
    if (fs.existsSync(logoPath)) {
      const relativePath = path.relative(clientPath, logoPath).replace(/\\/g, '/');
      return `./client-assets/${relativePath}`;
    }
  }
  return null;
}

// Generate client info file for runtime reference
function generateClientInfo(clientName, envName, config, outputPath, logoUrl, fontFiles = [], resolvedFontFamily = null) {
  const finalFontFamily = resolvedFontFamily || getResolvedFontFamily(config.widget?.fontFamily, fontFiles);
  const info = {
    client: clientName,
    environment: envName,
    generatedAt: new Date().toISOString(),
    config: {
      ...config.widget,
      fontFamily: finalFontFamily,
      fontFaces:           getFontFaceDescriptors(fontFiles, finalFontFamily),
      header:              config.header || {},
      apiGatewayEndpoint:  config.aws?.apiGatewayEndpoint || '',
      instanceId:          config.aws?.instanceId || '',
      contactFlowId:       config.aws?.contactFlowId || '',
    },
  };

  if (logoUrl) {
    info.assets = {logo: logoUrl};
  }

  const content = `/**
 * Current Client Configuration
 * Auto-generated - Do not edit manually
 */
window.__CHAT_CLIENT_INFO__ = ${JSON.stringify(info, null, 2)};
`;

  fs.writeFileSync(outputPath, content);
  console.log(`  ✅ Generated clientInfo.js`);
}

// Main execution
function main() {
  const args = parseArgs();
  
  // Check for help flag
  if (args.help || args.h) {
    console.log(`
Client Environment Preparation Script

Usage:
  npm run prepare -- --client=<client-name> --env=<environment>
  node scripts/prepare-client.js --client=<client-name> --env=<environment>

Options:
  --client    Client folder name (required)
  --env       Environment name: dev, qa, prod, etc. (required)
  --list      List all available clients
  --help, -h  Show this help message

Examples:
  npm run prepare -- --client=abc-corp --env=dev
  npm run prepare -- --client=xyz-bank --env=prod
  npm run prepare -- --list
`);
    process.exit(0);
  }
  
  // List clients if requested
  if (args.list) {
    console.log('\n📁 Available Clients:\n');
    listClients();
    console.log('');
    process.exit(0);
  }
  
  // Validate required arguments
  if (!args.client || !args.env) {
    console.error('❌ Missing required arguments: --client and --env\n');
    console.log('Usage: npm run prepare -- --client=<client-name> --env=<environment>');
    console.log('Example: npm run prepare -- --client=abc-corp --env=dev');
    console.log('\nRun with --help for more options');
    process.exit(1);
  }
  
  const clientName = args.client;
  const envName = args.env;
  
  console.log(`\n🚀 Preparing environment for client: ${clientName} (${envName})\n`);
  
  // Validate client and environment
  const {clientPath, envFile} = validateClientEnv(clientName, envName);
  
  // Read environment configuration
  const config = JSON.parse(fs.readFileSync(envFile, 'utf8'));
  config._meta = {client: clientName};
  
  // Define paths
  const localTestingDir = path.join(__dirname, '..', 'local-testing');
  const clientAssetsDir = path.join(clientPath, 'assets');
  const clientThemeDir = path.join(clientPath, 'theme');
  const clientFontsDir = path.join(clientPath, 'Fonts');
  const clientAssetsFontsDir = path.join(clientPath, 'assets', 'fonts');
  const outputAssetsDir = path.join(localTestingDir, 'client-assets');

  // Clean previous client assets
  if (fs.existsSync(outputAssetsDir)) {
    fs.rmSync(outputAssetsDir, {recursive: true});
    console.log('  🧹 Cleaned previous client assets');
  }

  // Copy client assets
  if (fs.existsSync(clientAssetsDir)) {
    copyDirSync(clientAssetsDir, outputAssetsDir);
    console.log('  ✅ Copied client assets');
  }

  // Allow overriding colors via CLI (--colorsFile or --primaryColor)
  if (args.colorsFile) {
    const source = path.resolve(args.colorsFile);
    if (fs.existsSync(source)) {
      try {
        fs.mkdirSync(clientThemeDir, {recursive: true});
        fs.copyFileSync(source, path.join(clientThemeDir, 'colors.json'));
        console.log('  ✅ Applied colors file to client theme');
      } catch (e) {
        console.warn('  ⚠️ Failed to apply colors file:', e.message);
      }
    } else {
      console.warn('  ⚠️ colors file not found:', source);
    }
  } else if (args.primaryColor) {
    const colorsPath = path.join(clientThemeDir, 'colors.json');
    try {
      let colors = {};
      if (fs.existsSync(colorsPath)) colors = JSON.parse(fs.readFileSync(colorsPath,'utf8'));
      colors.primary = colors.primary || {};
      colors.primary['500'] = args.primaryColor;
      fs.mkdirSync(clientThemeDir, {recursive:true});
      fs.writeFileSync(colorsPath, JSON.stringify(colors, null, 2));
      console.log('  ✅ Updated client primary color to', args.primaryColor);
    } catch (e) {
      console.warn('  ⚠️ Failed to update colors.json', e.message);
    }
  }

  // Copy theme files
  if (fs.existsSync(clientThemeDir)) {
    copyDirSync(clientThemeDir, path.join(outputAssetsDir, 'theme'));
    console.log('  ✅ Copied theme files');
  }

  // Copy font files for client-specific font families
  if (fs.existsSync(clientFontsDir)) {
    copyDirSync(clientFontsDir, path.join(outputAssetsDir, 'Fonts'));
  }
  if (fs.existsSync(clientAssetsFontsDir)) {
    copyDirSync(clientAssetsFontsDir, path.join(outputAssetsDir, 'Fonts'));
  }
  if (fs.existsSync(clientFontsDir) || fs.existsSync(clientAssetsFontsDir)) {
    console.log('  ✅ Copied font assets');
  }

  const fontFiles = getClientFontFiles(clientPath);
  let resolvedFontFamily = getResolvedFontFamily(config.widget.fontFamily, fontFiles, clientPath);

  config.widget.fontFamily = resolvedFontFamily;
  console.log('  🔎 Detected font files:', fontFiles.length);
  console.log('  🔎 Font file samples:', fontFiles.slice(0, 4).map(file => file.relativePath).join(', '));
  console.log('  🔎 Resolved font family:', resolvedFontFamily);

  // Generate configuration files
  generateBackendEndpoint(config, path.join(localTestingDir, 'backendEndpoint.js'));

  const logoUrl = getClientLogoUrl(clientPath);
  generateClientInfo(clientName, envName, config, path.join(localTestingDir, 'clientInfo.js'), logoUrl, fontFiles, resolvedFontFamily);
  generateClientThemeCss(config.widget, config.header || {}, path.join(localTestingDir, 'client-theme.css'), fontFiles, resolvedFontFamily);
  const envStateFile = path.join(__dirname, '..', '.client-env');
  fs.writeFileSync(envStateFile, JSON.stringify({client: clientName, env: envName}, null, 2));
  console.log('  ✅ Saved current client/env state');
  
  console.log(`\n✨ Environment ready! Client: ${clientName}, Env: ${envName}`);
  console.log(`   Run "npm run dev" to start the development server\n`);
}

// Run
main();
