/**
  * Backend Endpoint Configuration
  * Auto-generated by prepare-client.js
  * 
  * Client: demo-client
  * Environment: dev
  * Generated: 2026-07-07T13:36:28.997Z
  * 
  * DO NOT EDIT MANUALLY - Changes will be overwritten
  * Edit the source config at: clients/demo-client/config/env.dev.json
  */

  var contactFlowId = "1407b098-6ecb-4f04-a060-1c6272ebb316";
  var instanceId = "479fc682-9f32-45c8-9f2c-0b5d713b3c6c";
  var apiGatewayEndpoint = "";
  var snippetId = "QVFJREFIaFQ5MHpFSUtITkw4aWhjVFRTQ2xYNVRrZzZSNS9hc1gwdVNKbzBYYmJUUWdFZG9mYURkK2E2bXlUdVhtQnpETDBGQUFBQWJqQnNCZ2txaGtpRzl3MEJCd2FnWHpCZEFnRUFNRmdHQ1NxR1NJYjNEUUVIQVRBZUJnbGdoa2dCWlFNRUFTNHdFUVFNZjJqaHNPbXJWQXY0RGpoL0FnRVFnQ3VLWFkrdlFXMWZONkpibGRoNEZQLytWN09aaEx0NlYxMDEwbVI1NDcxZnU3MWVNZXJPNVdEcTh0aFc6OjhadS9vMnMzQnI2RHBFTzI4WUlJMnFPa2UvQSsvZXhVMnJHMVoyb24rcTV4N1l5bW1iaVhvSTBNUDdlWDRNSDhiUC84R096UC9lanBLVjkvL05iMXpaUEhMM2pYTkF5VnJReHkwSmNvc1FGMDQ0Yk8zSmNGMmNzOFFoVWRzbVFKMlA3bjdYTVRmejVKeUNKVmZxZTNucEl1WGpqT1kvRT0=')";
  var region = "us-west-2";

  // Additional config (optional - for enhanced widget features)
  var widgetConfig = {
    title: "Demo Support",
    subtitle: "How can we help you today?",
    primaryColor: "#1976D2",
    secondaryColor: "#FFC107",
    headerTextColor: "#FFFFFF",
    fontFamily: "Roboto"
  };

  var featureFlags = {
    enableAttachments: true,
    enableTypingIndicator: true,
    enableReadReceipts: true,
    enableSounds: false
  };
  