/**
  * Backend Endpoint Configuration
  * Auto-generated by prepare-brand.js
  *
  * Brand: estee-lauder
  * Environment: dev
  * Generated: 2026-07-15T12:44:21.098Z
  *
  * DO NOT EDIT MANUALLY - Changes will be overwritten
  * Edit the source config at: brands/estee-lauder/config/env.dev.json
  */

  var contactFlowId = "e04fb45a-e292-4150-995a-f08b88c86965";
  var instanceId = "9cda7725-37d6-4d3f-a4b5-77acfeb2879b";
  var apiGatewayEndpoint = "https://sd7r0a30a5.execute-api.eu-west-2.amazonaws.com/test/startChat";
  var snippetId = "QVFJREFIaUYzWWsrMWRnRDlkczNlcXlOOW53N0RzaVdJdlpUUXhxcmxDcHgzM0xWdXdFOWd4ZzBPek1jclQ5Sm1RbU1SdFZFQUFBQWJqQnNCZ2txaGtpRzl3MEJCd2FnWHpCZEFnRUFNRmdHQ1NxR1NJYjNEUUVIQVRBZUJnbGdoa2dCWlFNRUFTNHdFUVFNZmdNS0ZTeDRkazY1cllaY0FnRVFnQ3VTZng5N2xUM1Z3bFYrQkNyUjRLZmdGTmYwdkhaSVAvaHJOVGErTENlOUVzNGhiQnkyWVNZSURpVW06Om15L01OMThVc0RkTXF0VENZbk1FUEh0UGduMDZIb0J4aFF2T2l3dVN3elZHSEtQNU4wZGVkMjNPUnNXYW9vU2lSY1JKb0NtS3BqTWN4c0JkVGhLQWJDSTlpYmdaVFdKREREcitjeUdnTFhsOHAzZXd0RHluMFNMTU1hdk0zM2NwZnlONTBkSWYyRmd2TG9pUTB1UHRneWRyelR2N2JDOD0=";
  var region = "eu-west-2";

  // Additional config (optional - for enhanced widget features)
  var widgetConfig = {
    title: "Estee Lauder",
    subtitle: "We're here to help",
    primaryColor: "#3F51B5",
    secondaryColor: "#FF4081",
    headerTextColor: "#FFFFFF",
    fontFamily: "Optima LT Std Display"
  };

  var featureFlags = {
    enableAttachments: true,
    enableTypingIndicator: true,
    enableReadReceipts: true,
    enableSounds: false
  };
  