/**
  * Backend Endpoint Configuration
  * Auto-generated by prepare-client.js
  * 
  * Client: estee-lauder
  * Environment: dev
  * Generated: 2026-07-09T11:39:28.456Z
  * 
  * DO NOT EDIT MANUALLY - Changes will be overwritten
  * Edit the source config at: clients/estee-lauder/config/env.dev.json
  */

  var contactFlowId = "YOUR_CONTACT_FLOW_ID";
  var instanceId = "YOUR_CONNECT_INSTANCE_ID";
  var apiGatewayEndpoint = "[your_instance.my.connect.aws](https://YOUR_INSTANCE.my.connect.aws/connectwidget/api/YOUR_WIDGET_ID/start)";
  var snippetId = "YOUR_SNIPPET_ID";
  var region = "us-west-2";

  // Additional config (optional - for enhanced widget features)
  var widgetConfig = {
    title: "estee-lauder Support",
    subtitle: "We're here to help",
    primaryColor: "#3F51B5",
    secondaryColor: "#FF4081",
    headerTextColor: "#FFFFFF",
    fontFamily: "Optima LT Std Display"
  };

  var featureFlags = {
    enableAttachments: true,
    enableTypingIndicator: true,
    enableReadReceipts: true,
    enableSounds: false
  };
  